const recipes = [
  {
    id: 1,
    name: "Delicious Pasta",
    tagline: "Creamy comfort in every bite!",
    image: "imgs/Pasta.jpg",
    servings: 2,
    difficulty: "Easy",
    cuisine: "Italian",
    category: "Main Dish",
    tips: "Add chili flakes for a spicy kick!",
    rating: 4.7,
    ingredients: [
      "200g spaghetti",
      "2 cloves garlic",
      "100ml heavy cream",
      "50g parmesan cheese",
      "2 tbsp olive oil",
      "Salt and pepper to taste",
      "Fresh parsley for garnish",
    ],
    steps: [
      "Boil spaghetti in salted water until al dente.",
      "Heat olive oil in a pan and sauté garlic until fragrant.",
      "Add heavy cream and let it simmer for 2 minutes.",
      "Stir in parmesan cheese until melted and creamy.",
      "Toss the cooked spaghetti in the sauce.",
      "Season with salt and pepper.",
      "Garnish with fresh parsley and serve immediately.",
    ],
  },
  {
    id: 2,
    name: "Fresh Salad",
    tagline: "Healthy never tasted this good!",
    image: "imgs/salad.jpg",
    servings: 2,
    difficulty: "Very Easy",
    cuisine: "Mediterranean",
    category: "Side Dish",
    tips: "Use lemon juice instead of vinegar for a zesty twist.",
    rating: 4.5,
    ingredients: [
      "Mixed greens (lettuce, spinach, arugula)",
      "1 cucumber, sliced",
      "10 cherry tomatoes, halved",
      "50g feta cheese, crumbled",
      "2 tbsp olive oil",
      "1 tbsp balsamic vinegar",
      "Salt and pepper to taste",
    ],
    steps: [
      "Wash and dry the greens thoroughly.",
      "Slice cucumber and halve cherry tomatoes.",
      "In a large bowl, mix greens, cucumber, tomatoes, and feta.",
      "Drizzle olive oil and balsamic vinegar over the salad.",
      "Season with salt and pepper.",
      "Toss everything gently and serve fresh.",
    ],
  },
  {
    id: 3,
    name: "Chocolate Cake",
    tagline: "Indulge in every rich slice!",
    image: "imgs/Chocolate cake.jpg",
    servings: 6,
    difficulty: "Medium",
    cuisine: "French",
    category: "Dessert",
    tips: "Add a pinch of instant coffee to enhance the chocolate flavor.",
    rating: 4.9,
    ingredients: [
      "200g all-purpose flour",
      "200g sugar",
      "100g cocoa powder",
      "1 tsp baking powder",
      "1/2 tsp baking soda",
      "2 eggs",
      "100ml milk",
      "100ml vegetable oil",
      "1 tsp vanilla extract",
      "100ml boiling water",
    ],
    steps: [
      "Preheat oven to 180°C (350°F) and grease a cake pan.",
      "In a bowl, mix flour, sugar, cocoa powder, baking powder, and baking soda.",
      "Add eggs, milk, oil, and vanilla extract. Mix until smooth.",
      "Carefully stir in boiling water (batter will be thin).",
      "Pour batter into the cake pan and bake for 30–35 minutes.",
      "Cool completely before serving.",
    ],
  },
  {
    id: 4,
    name: "Grilled Chicken",
    tagline: "Juicy, tender, and full of flavor!",
    image: "imgs/grilled_chicken.jpg",
    servings: 4,
    difficulty: "Easy",
    cuisine: "American",
    category: "Main Dish",
    tips: "Marinate chicken for 30 minutes for extra flavor.",
    rating: 4.6,
    ingredients: [
      "4 chicken breasts",
      "2 tbsp olive oil",
      "1 tsp paprika",
      "1 tsp garlic powder",
      "Salt and pepper to taste",
      "Fresh lemon juice",
    ],
    steps: [
      "Preheat grill to medium-high heat.",
      "Rub chicken with olive oil, paprika, garlic powder, salt, and pepper.",
      "Grill chicken for 6-8 minutes per side until cooked through.",
      "Squeeze fresh lemon juice over the chicken before serving.",
    ],
  },
  {
    id: 5,
    name: "Avocado Toast",
    tagline: "Simple, healthy, and delicious!",
    image: "imgs/avocado_toast.jpg",
    servings: 1,
    difficulty: "Very Easy",
    cuisine: "American",
    category: "Breakfast",
    tips: "Add a poached egg on top for extra protein.",
    rating: 4.4,
    ingredients: [
      "2 slices of bread",
      "1 ripe avocado",
      "Salt and pepper to taste",
      "Red pepper flakes",
      "1 tsp olive oil",
    ],
    steps: [
      "Toast the bread slices until golden brown.",
      "Mash avocado and season with salt and pepper.",
      "Spread avocado over the toast.",
      "Drizzle olive oil and sprinkle red pepper flakes on top.",
      "Serve immediately.",
    ],
  },
  {
    id: 6,
    name: "Berry Smoothie",
    tagline: "A refreshing burst of antioxidants!",
    image: "imgs/berry_smoothie.jpg",
    servings: 2,
    difficulty: "Easy",
    cuisine: "International",
    category: "Drink",
    tips: "Use frozen berries to make it extra cold and thick.",
    rating: 4.8,
    ingredients: [
      "1 cup mixed berries",
      "1 banana",
      "1 cup yogurt",
      "1/2 cup milk",
      "1 tsp honey",
    ],
    steps: [
      "Combine all ingredients in a blender.",
      "Blend until smooth.",
      "Pour into a glass and serve chilled.",
    ],
  },
  {
    id: 7,
    name: "Pancakes",
    tagline: "Fluffy and perfect for breakfast!",
    image: "imgs/pancakes.jpg",
    servings: 4,
    difficulty: "Easy",
    cuisine: "American",
    category: "Breakfast",
    tips: "Don’t overmix the batter; lumps are okay.",
    rating: 4.7,
    ingredients: [
      "200g all-purpose flour",
      "2 tbsp sugar",
      "1 tsp baking powder",
      "1/2 tsp baking soda",
      "1/4 tsp salt",
      "2 eggs",
      "250ml milk",
      "2 tbsp melted butter",
    ],
    steps: [
      "Mix dry ingredients in a bowl.",
      "Whisk eggs, milk, and melted butter together.",
      "Combine wet and dry ingredients until smooth.",
      "Heat a non-stick pan and pour batter to form pancakes.",
      "Cook until bubbles form, then flip and cook the other side.",
      "Serve with syrup or toppings of choice.",
    ],
  },
  {
    id: 8,
    name: "Tomato Soup",
    tagline: "Warm and comforting in every spoonful!",
    image: "imgs/tomato_soup.jpg",
    servings: 4,
    difficulty: "Easy",
    cuisine: "Italian",
    category: "Soup",
    tips: "Serve with a swirl of cream or fresh basil on top.",
    rating: 4.6,
    ingredients: [
      "500g tomatoes, chopped",
      "1 onion, chopped",
      "2 cloves garlic",
      "2 tbsp olive oil",
      "500ml vegetable broth",
      "Salt and pepper to taste",
      "Fresh basil leaves",
    ],
    steps: [
      "Heat olive oil in a pot and sauté onion and garlic.",
      "Add tomatoes and cook until soft.",
      "Pour in vegetable broth and simmer for 15 minutes.",
      "Blend until smooth.",
      "Season with salt, pepper, and garnish with basil.",
    ],
  },
  {
    id: 9,
    name: "Beef Stir Fry",
    tagline: "Quick, tasty, and full of veggies!",
    image: "imgs/beef_stir_fry.jpg",
    servings: 3,
    difficulty: "Medium",
    cuisine: "Asian",
    category: "Main Dish",
    tips: "Serve immediately to keep vegetables crisp.",
    rating: 4.7,
    ingredients: [
      "300g beef strips",
      "1 bell pepper, sliced",
      "1 carrot, julienned",
      "2 tbsp soy sauce",
      "1 tbsp sesame oil",
      "2 cloves garlic",
      "Salt and pepper to taste",
    ],
    steps: [
      "Heat sesame oil in a pan and sauté garlic.",
      "Add beef strips and cook until browned.",
      "Add vegetables and stir fry for 3-5 minutes.",
      "Pour soy sauce and mix well.",
      "Serve hot with rice or noodles.",
    ],
  },
  {
    id: 10,
    name: "Veggie Omelette",
    tagline: "Protein-packed and colorful!",
    image: "imgs/veggie_omelette.jpg",
    servings: 1,
    difficulty: "Easy",
    cuisine: "International",
    category: "Breakfast",
    tips: "Add cheese for extra flavor.",
    rating: 4.5,
    ingredients: [
      "3 eggs",
      "1/2 bell pepper, diced",
      "1/2 onion, diced",
      "1/2 tomato, chopped",
      "Salt and pepper to taste",
      "1 tsp olive oil",
    ],
    steps: [
      "Beat the eggs with salt and pepper.",
      "Heat olive oil in a pan and sauté vegetables for 2 minutes.",
      "Pour eggs over vegetables and cook until set.",
      "Fold omelette and serve warm.",
    ],
  },
  {
    id: 11,
    name: "Spicy Tacos",
    tagline: "A fiesta in every bite!",
    image: "imgs/spicy_tacos.jpg",
    servings: 4,
    difficulty: "Medium",
    cuisine: "Mexican",
    category: "Main Dish",
    tips: "Serve with lime wedges and hot sauce.",
    rating: 4.6,
    ingredients: [
      "8 taco shells",
      "300g minced beef",
      "1 onion, chopped",
      "1 tsp chili powder",
      "1 tsp cumin",
      "Lettuce, chopped",
      "Cheddar cheese, grated",
      "Salsa",
    ],
    steps: [
      "Cook minced beef with onion, chili powder, and cumin until browned.",
      "Warm taco shells in oven.",
      "Fill shells with beef, lettuce, cheese, and salsa.",
      "Serve immediately.",
    ],
  },
  {
    id: 12,
    name: "Banana Muffins",
    tagline: "Sweet, soft, and perfect for snacks!",
    image: "imgs/banana_muffins.jpg",
    servings: 6,
    difficulty: "Easy",
    cuisine: "American",
    category: "Dessert",
    tips: "Ripe bananas make muffins sweeter and moister.",
    rating: 4.8,
    ingredients: [
      "3 ripe bananas",
      "200g flour",
      "100g sugar",
      "1 tsp baking powder",
      "1/2 tsp baking soda",
      "1/4 tsp salt",
      "1 egg",
      "50ml vegetable oil",
    ],
    steps: [
      "Preheat oven to 180°C and grease muffin tray.",
      "Mash bananas and mix with egg and oil.",
      "Combine flour, sugar, baking powder, baking soda, and salt.",
      "Mix wet and dry ingredients until smooth.",
      "Pour batter into muffin cups and bake 20-25 minutes.",
    ],
  },
  {
    id: 13,
    name: "Grilled Salmon",
    tagline: "Tender, flaky, and full of flavor!",
    image: "imgs/grilled_salmon.jpg",
    servings: 2,
    difficulty: "Medium",
    cuisine: "American",
    category: "Main Dish",
    tips: "Do not overcook, keep salmon moist.",
    rating: 4.9,
    ingredients: [
      "2 salmon fillets",
      "2 tbsp olive oil",
      "1 tsp garlic powder",
      "Salt and pepper to taste",
      "Lemon wedges",
    ],
    steps: [
      "Preheat grill to medium heat.",
      "Brush salmon with olive oil and season with garlic, salt, and pepper.",
      "Grill salmon 4-5 minutes per side until cooked.",
      "Serve with lemon wedges.",
    ],
  },
  {
    id: 14,
    name: "Caprese Salad",
    tagline: "Fresh, simple, and delicious!",
    image: "imgs/caprese_salad.jpg",
    servings: 2,
    difficulty: "Very Easy",
    cuisine: "Italian",
    category: "Side Dish",
    tips: "Drizzle balsamic glaze for extra sweetness.",
    rating: 4.7,
    ingredients: [
      "2 large tomatoes, sliced",
      "200g mozzarella, sliced",
      "Fresh basil leaves",
      "2 tbsp olive oil",
      "Salt and pepper to taste",
      "Balsamic glaze (optional)",
    ],
    steps: [
      "Arrange tomato and mozzarella slices alternately on a plate.",
      "Tuck basil leaves between slices.",
      "Drizzle olive oil and balsamic glaze on top.",
      "Season with salt and pepper and serve immediately.",
    ],
  },
];
